# GET USERS
GET http://localhost:3333/users
Content-Type: application/json

###

#DELETE USERS
DELETE http://localhost:3333/users
Content-Type: application/json

###

#UPDATED STATUS 
PUT http://localhost:3333/users
Content-Type: application/json

###

# GET UNIQUE USER
GET http://localhost:3333/users/06474a74-580e-4800-901c-be54fb3ebde6
Content-Type: application/json

###

# POST NEW USER
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Jessica ferreira",
  "email": "jessicaferreira@gmail.com"
}

###

#POST Create Todo
POST http://localhost:3333/todos
Content-Type: application/json
x-user-id: 06474a74-580e-4800-901c-be54fb3ebde6

{
  "title": "Task #6"
}

###
# Create Checkout
POST http://localhost:3333/checkout
Content-Type: application/json
x-user-id: 6987b872-f5f0-497b-99ad-11dfc1f19930
