# GET USERS
GET http://localhost:3333/users
Content-Type: application/json

###

#DELETE USERS
DELETE http://localhost:3333/users
Content-Type: application/json

###

# GET UNIQUE USER
GET http://localhost:3333/users/fd6db786-9e6f-4d47-8c1e-0ea2783917bf
Content-Type: application/json

###

# POST NEW USER
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Hamiceis Pereira mendonca",
  "email": "hamiceis@gmail.com"
}

###

#POST Create Todo
POST http://localhost:3333/todos
Content-Type: application/json
x-user-id: fd6db786-9e6f-4d47-8c1e-0ea2783917bf

{
  "title": "Minha primeira tarefa"
}

###
# Create Checkout
POST http://localhost:3333/checkout
Content-Type: application/json
x-user-id: b518474b-6199-4f56-9161-aa8bc84d509b

